### ISSUE TITLE
Any plans to offer licensing?

### ISSUE THREAD

**Issue by ghost** [GDCASU/Twisted-Sails#139]
I'd love to borrow some ideas from this or add back to the project. I like the club approach you are doing too with game dev. Any way to license this or contact someone for more info / permission to use code and / or cross promote.

**Comment by spaceperson** [comment]
I messaged the president in charge of the old project and he replied with,
"I do not have any control of the game nor say". To my knowledge, nobody is
working on the Twisted Sails project anymore. The code is likely outdated
because it was built using an older version of Unity. Game mechanics aren't
copyrightable if you just want to copy the mechanics or game style. However
the mechanics are bad in my opinion, somebody had the brilliant idea to
make the cannons shoot sideways like real ships, but it doesn't work very
well gameplay wise. As for the code, it's available on github but because
it was a college club project the legal use of the code and assets aren't
in control of the creators, it technically belongs to ASU. I'm not sure
what policies ASU has on that or who at ASU you could contact but I doubt
anybody would mind if you use it.

**Comment by ghost** [comment]
Good info. Thank you for taking the time, I can run with it from there.
